### ISSUE TITLE
Wireframe: Map

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#100]
#### Description:

Develop wireframes for the map page, addresses:
- #106 
- #105 
- #109 
- Question: #107 
   - we are aiming for drawing polygons

#### Checklist:

- [x] initial conversation to identify current understanding of needs, where further research is needed
- [x] explore how results can be displayed across screens
- [x] understand constraints/limits based on library

**Comment by pavelcreates** [comment]
Updates of the map mockups are in this section:

https://www.figma.com/design/74nNxjyv6JM6hiT1FluULV/OMRR-(ORI)?node-id=779-29632&t=7Z0bYHcn1KZ2PS3R-4

**Comment by dawnbcgov** [comment]
These were reviewed and signed off by Product Owner on 2024-06-19 🎉
