### ISSUE TITLE
Wireframe: Authorization Details (updated)

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#101]
#### Description:

Develop wireframes for the updated and expanded authorization details page, addresses:
- #112 
- #113
    - Job status in wireframes (updated in Mural)  

#### Checklist:

- [x] initial conversation to identify current understanding of needs, where further research is needed

**Comment by pavelcreates** [comment]
Link to updated mockups:

https://www.figma.com/design/74nNxjyv6JM6hiT1FluULV/OMRR-(ORI)?node-id=823-26252&t=7Z0bYHcn1KZ2PS3R-4

**Comment by dawnbcgov** [comment]
These were reviewed and signed off by Product Owner on 2024-06-19 🎉
