### ISSUE TITLE
Add details on process and legislation to site

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#104]
#### Description:

Currently we link out to relevant sections of the gov.bc.ca website. We have some content we wondered if should be directly on the app from MVP phase:
- government contacts 
- how notification and permitting processes work
 
#### Dependencies:

- Relates to #103 
- Relates to #158 

#### Definition of Ready:

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)

**Comment by dawnbcgov** [comment]
Requires decision from program area to determine whether to proceed, and if so content for #158

**Comment by kdbelair** [comment]
We will proceed with hosting government contact information on Organics Info. We will continue to link externally for how the notification and permitting processes work.

**Comment by dawnbcgov** [comment]
Okay great, closing this then :)
