### ISSUE TITLE
Show map layers with ability to toggle them

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#109]
#### Description:

Show map layers published by gov with ability to toggle them on/off:

Aquifers and Water Wells 
- [Aquifers - All](https://catalogue.data.gov.bc.ca/dataset/099d69c5-1401-484d-9e19-c121ccb7977c)  
- [Aquifers - Vulnerability](https://catalogue.data.gov.bc.ca/dataset/099d69c5-1401-484d-9e19-c121ccb7977c)  
- [Aquifers - Subtype](https://catalogue.data.gov.bc.ca/dataset/099d69c5-1401-484d-9e19-c121ccb7977c)  
- [Sea Water Intrusion Vulnerability - Outlined](https://catalogue.data.gov.bc.ca/dataset/cc4b73c7-c16c-48eb-a069-642cafb5dec5)  
- [Sea Water Intrusion Vulnerability - Unconsolidated Aquifers](https://catalogue.data.gov.bc.ca/dataset/cc4b73c7-c16c-48eb-a069-642cafb5dec5)  
- [Sea Water Intrusion Vulnerability - Bedrock Aquifers](https://catalogue.data.gov.bc.ca/dataset/cc4b73c7-c16c-48eb-a069-642cafb5dec5)  
- [Groundwater Wells – All](https://catalogue.data.gov.bc.ca/dataset/groundwater-wells) 

Water Licensing 
- [Water Rights - Applications](https://catalogue.data.gov.bc.ca/dataset/f3a53d7f-da09-4726-ac83-f0032e4bd490)  
- [Water Rights - Licences](https://catalogue.data.gov.bc.ca/dataset/5549cae0-c2b1-4b96-9777-529d9720803c)  

Watersheds 
- [Community Watersheds](https://catalogue.data.gov.bc.ca/dataset/bc57faf7-23e4-43fe-918a-e999936dbafa)
- [Major Watersheds - Outlined](https://catalogue.data.gov.bc.ca/dataset/8ded3f62-e647-4f00-a115-10753419f466)  
- [FWA - Watershed Groups - Outlined](https://catalogue.data.gov.bc.ca/dataset/51f20b1a-ab75-42de-809d-bf415a0f9c62)  
- [FWA - Named Watersheds - Outlined](https://catalogue.data.gov.bc.ca/dataset/ea63ea04-eab0-4b83-8729-f8a93ac688a1)  

Freshwater Atlas 
- [FWA Stream Network](https://catalogue.data.gov.bc.ca/dataset/freshwater-atlas-stream-network) 
- [FWA Wetlands](https://catalogue.data.gov.bc.ca/dataset/freshwater-atlas-wetlands) 
- [FWA Linear Boundaries](https://catalogue.data.gov.bc.ca/dataset/freshwater-atlas-linear-boundaries) 
- [FWA Lakes](https://catalogue.data.gov.bc.ca/dataset/freshwater-atlas-lakes) 

Agricultural Land Reserve 
- [ALC ALR Polygons](https://catalogue.data.gov.bc.ca/dataset/92e17599-ac8a-47c8-877c-107768cb373c)  
- [ALC Agricultural Land Reserve Lines](https://catalogue.data.gov.bc.ca/dataset/b23a6be5-c7b0-4a12-a598-bb369a159be1)  
- [ALR Notices of Intent (Spatial View)](https://catalogue.data.gov.bc.ca/dataset/43e45e82-b5d8-46a3-bb28-f2b7223423fc)  

Water License Points of Diversion 
- [Water points of diversion - Licensed Springs, joined with license information](https://catalogue.data.gov.bc.ca/dataset/4bc1cf40-3507-4591-bd89-82e8809440b5)  
- [Water points of diversion - Drinking Water Sources, consumptive water license points](https://catalogue.data.gov.bc.ca/dataset/bd3566ed-1101-473b-a3ec-5daefa1fe2c1)  

Wildlife Species at Risk 
- [Critical Habitat for federally-listed species at risk](https://catalogue.data.gov.bc.ca/dataset/076b8c98-a3f1-429b-9dae-03faed0c6aef)  

Crown Lands  
- [PMBC Parcel Cadastre](https://catalogue.data.gov.bc.ca/dataset/4cf233c2-f020-4f7a-9b87-1923252fbc24)

Notes
- <mark>(could not find a "Existing Agricultural Land Reserve (ALR) authorizations" layer)</mark>

#### Users:

| User | User type | 
|------|-----------|
| Medical Health Officer | External User |
| Staff of Provincial Agricultural Land Commission | External User |
| Public | External User | External User |

#### Dependencies:

- Relates to #106 

#### Definition of Ready:

- [x] User role and type are identified
- [x] Wireframes are included
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)

#### Definition of Done:

- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by dawnbcgov** [comment]
Thanks @kdbelair I have edited the top comment to include those :)

**Comment by ccallendar** [comment]
@dawnbcgov there is one link above - [ALR Notices of Intent (Spatial View)](https://catalogue.data.gov.bc.ca/dataset/43e45e82-b5d8-46a3-bb28-f2b7223423fc) - that doesn't have a WMS tile layer url. Should we still display it (disabled?) or just not show it?

**Comment by dawnbcgov** [comment]
@kdbelair see this comment from @ccallendar, I wonder if we could see if there is a different source to get those Notices of Intent displayed? I'm seeing this: https://www.alc.gov.bc.ca/contact#maps-gis

@ccallendar -- my sense would be to not show it while we sort out a different source but defer to Konane.

**Comment by kdbelair** [comment]
Let's not show the layer while we try to sort out a different source. I will reach out to one of the ALS GIS staff to see if they are aware of another source.

**Comment by webgismd** [comment]
> @dawnbcgov there is one link above - [ALR Notices of Intent (Spatial View)](https://catalogue.data.gov.bc.ca/dataset/43e45e82-b5d8-46a3-bb28-f2b7223423fc) - that doesn't have a WMS tile layer url. Should we still display it (disabled?) or just not show it?

This layer is in an IDIR only authenticated WMS/WFS services see test: 

https://test.apps.gov.bc.ca/ext/sgw/geo.allgov?version=1.3.0&request=getcapabilities&service=wfs

**Comment by kdbelair** [comment]
@ccallendar. I received the following response for CITZ, let me know if it helps. I am going to submit a ticket to request the WMS url gets added back to the catalogue record.

The following wms should be a resource link in the catalogue record you referenced: [openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_NOI_SV/ows?service=WMS&request=GetCapabilities](https://openmaps.gov.bc.ca/geo/pub/WHSE_LEGAL_ADMIN_BOUNDARIES.OATS_ALR_NOI_SV/ows?service=WMS&request=GetCapabilities)

**Comment by kdbelair** [comment]
@ccallendar I have reviewed all the layers on ORI and have the following feedback:

1)	Rename “Water points of diversion – Drinking Water Sources, consumptive water license points” to “Water Licence Points of Diversion – Drinking Water Sources”
2)	Rename “Water points of Diversion – Licensed Springs, joined with licence information” to Water Licence Points of Diversion – Springs”
3)	The “Water points of diversion – Drinking Water Sources, consumptive water license points” layer dots currently show up as grey on the map and are very difficult to see. They currently show up as green on iMapBC so it would be preferable if they were a similar more obvious colour.
4)	The “Water points of Diversion – Licensed Springs, joined with licence information” layer currently show up as red and grey dots. The grey dots are difficult to see. On iMapBC they are green and black and we would like something similar so they are easier to see.
5)	Rename “PMBC Parcel Cadastre” to “PMBC Parcle Cadastre – Crown Provincial”
6)	Capitalize the words for the layer under Wildlife Species at Risk
7)	The critical habitat layer currently overlays a solid yellow polygon. It would be helpful if we can change it to being transparent or partially transparent as it is in iMapBC.
8)	The proposed ALR Notices of Intent layer can be replaced by the ALR Applications layer at the following link. Time permitting, we are hoping we get ALR to restore the data for Notices of Intent and also include that layer https://catalogue.data.gov.bc.ca/dataset/48165eb9-cd44-4c3a-a178-ab5c0b9d9ebc

**Comment by kdbelair** [comment]
@ccallendar Please also include the following layer:
https://catalogue.data.gov.bc.ca/dataset/indian-reserves-and-band-names-administrative-boundaries

**Comment by ccallendar** [comment]
Thanks for the feedback @kdbelair ! I've made a new ticket to capture the changes needed:
https://github.com/bcgov/nr-epd-organics-info/issues/204
