### ISSUE TITLE
Revise and draft content for v1

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#158]
#### Description:

Revise and develop new content for v1 based on outcomes of feedback and early service design research. 

#### Development Checklist:

- [x] host initial review of content requests and prioritize
- [x] first draft, added to wireframes
- [x] review
- [x] final sign-off

#### Definition of Ready:

- [x] Wireframes are included
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)

#### Definition of Done:

- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by dawnbcgov** [comment]
We have a first draft scaffolding this content in the wireframes, it is with the program area for review and changes.

**Comment by kdbelair** [comment]
Content reviewed and revisions have been made. Approved to proceed with content.

**Comment by dawnbcgov** [comment]
This was updated awhile ago in the wireframes, closing as done.
