### ISSUE TITLE
Add OSM Grayscale feature flag

### ISSUE THREAD

**Issue by ccallendar** [bcgov/nr-epd-organics-info#211]
#### Description:

Add new feature flag environment variable on the Map page that when turned on, will make the OSM (Open Street Map) tiles rendered in grayscale.

#### Definition of Ready:

- [x] Design / Solution is accepted by Product Owner

#### Definition of Done:

- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by dawnbcgov** [comment]
Merged in: https://github.com/bcgov/nr-epd-organics-info/pull/213
