### ISSUE TITLE
Figure out if there is an air boundary layer we could include

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#293]

**Comment by dawnbcgov** [comment]
I reviewed the existing data products, and we have:

- [Venting Index Zones](https://www2.gov.bc.ca/assets/gov/environment/air-land-water/air/reports-pub/prov_overview_venting_index_zones.pdf)
- [Venting Index Forecast Map](https://governmentofbc.maps.arcgis.com/apps/webappviewer/index.html?id=6d288bc667b24528a5c1e3b4c0373d07)

but there are also:

- [Air Zones (seen in the air zone reports)](https://www2.gov.bc.ca/assets/gov/environment/air-land-water/air/reports-pub/air-zone-reports/2019-2021/air_zone_report_2019_2021.pdf)

--

Spatial files for us:

- Air Zones:  https://catalogue.data.gov.bc.ca/dataset/british-columbia-air-zones
- Ventilation Index Forecast Zones:  https://catalogue.data.gov.bc.ca/dataset/ventilation-index-forecast-zones

**Comment by dawnbcgov** [comment]
@kdbelair can you review this and provide feedback?

**Comment by kdbelair** [comment]
I have reviewed with staff from the OMMR policy team and authorizations and understand there is not an air boundary layer that would be relevant for OMRR and Organics Info.

**Comment by dawnbcgov** [comment]
Great let's close this then!
