### ISSUE TITLE
explore Direct link to NRCED from auth details page for C&E information

### ISSUE THREAD

**Issue by mishraomp** [bcgov/nr-epd-organics-info#302]
@dawnbcgov , for you it is just fyi...

Found this API link to query data, which could be explored.

docs:

https://nrpti-api-f00029-prod.apps.silver.devops.gov.bc.ca/api/docs

call from UI

https://nrpti-api-f00029-prod.apps.silver.devops.gov.bc.ca/api/public/search?dataset=OrderNRCED,InspectionNRCED,RestorativeJusticeNRCED,AdministrativePenaltyNRCED,AdministrativeSanctionNRCED,TicketNRCED,WarningNRCED,CourtConvictionNRCED,CorrespondenceNRCED,DamSafetyInspectionNRCED,ReportNRCED&pageNum=0&pageSize=25&sortBy=-dateIssued&fields=

RE: NRCED... We were told that one of the facilities recently had a pollution order,  so were exploring how to search and view that info.  This is my chat with Harry:

 

I think I found the pollution order: https://nrced.gov.bc.ca/records;autofocus=668eb323556fa0001bbe7850
so now I want to see if it's in ams Oops no, this one: https://nrced.gov.bc.ca/records;autofocus=66390d74fed9710022e8b7ce
No.
BUT/AND using the auth to search only grabs inspections: 111557
https://nrced.gov.bc.ca/records;keywords=111557;ms=486;currentPage=1;pageSize=25;sortBy=-dateIssued
Other search: https://nrced.gov.bc.ca/records;keywords=111557%20OR%20%22G.T.%20FARMS%20LTD.%22;ms=569;currentPage=1;pageSize=25;sortBy=-dateIssued
 

Natural Resource Compliance and Enforcement Database

 

Repeating my point from the call: in NRCED some enforcement actions are by auth #, some are by name.   We may want to dig in with a application analyst with more details about how to do sophisticated queries

**Comment by mishraomp** [comment]
@imsunchips , looping you in, since this is a data integration

**Comment by mishraomp** [comment]
This query to the API returns search results when both Auth number and Regulated Party name is included, in the keywords of the api call
sample call
https://nrpti-api-f00029-prod.apps.silver.devops.gov.bc.ca/api/public/search?dataset=OrderNRCED,InspectionNRCED,RestorativeJusticeNRCED,AdministrativePenaltyNRCED,AdministrativeSanctionNRCED,TicketNRCED,WarningNRCED,CourtConvictionNRCED,CorrespondenceNRCED,DamSafetyInspectionNRCED,ReportNRCED&keywords=111557%20OR%20%22G.T.%20FARMS%20LTD.%22&pageNum=0&pageSize=25&sortBy=-dateIssued&fields=

**Comment by mishraomp** [comment]
grab this property from json array, for each element, to map directly to URL in NRCED.

`_id: "662a8ceaf460520022de9a09",`

for ex: `https://nrced.gov.bc.ca/records;autofocus=662a8ceaf460520022de9a09`

**Comment by dawnbcgov** [comment]
@dawnbcgov 
- [ ] check with harry what fields from this we need / want to display on the authorizations details page

**Comment by dawnbcgov** [comment]
Also I guess we have #260 for feature work once an approach is finalized?

**Comment by dawnbcgov** [comment]
@harryaolson is mocking up the decided approach! I will close this and we can use #260 for tracking feature development per my comment above 🎉
