### ISSUE TITLE
Auth Details > Add missing feedstock to "organic matter used for composting" section

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#315]
#### Description:

We identified a solution add the two feedstocks not present from #263. One is included in an updated query, for the other, there is only one authorization affected: https://organicsinfo.gov.bc.ca/authorization/111479

On that page, under "Organic Matter Used for Composting" we should also have a checkmark indicating it accepts "Red-meat waste" per the [Schedule 12 of the regulation has a “Table — Organic Matter Used for Composting”](https://www.bclaws.gov.bc.ca/civix/document/id/complete/statreg/18_2002#Schedule12).

#### Definition of Ready:

- [ ] Wireframes are included
- [x] Design / Solution is accepted by Product Owner
- [x] Dependencies are identified (technical, business, regulatory/policy)

**Comment by mishraomp** [comment]
@dawnbcgov should we name the new json field as `Red Meat Waste`

**Comment by dawnbcgov** [comment]
Sounds good to me! so I guess we need:
"Red Meat Waste": "Yes"
for 
Authorization 111479
