### ISSUE TITLE
Update C&E link on main page

### ISSUE THREAD

**Issue by dawnbcgov** [bcgov/nr-epd-organics-info#90]
Note: MVP task moved over from previous requirements document.

Description: 

Update compliance and enforcement (C&E) link on main page to https://www2.gov.bc.ca/gov/content/environment/research-monitoring-reporting/reporting/environmental-enforcement-reporting.

We anticipate that users might want to search related C&E decisions and the current link is more of an overview of those activities generally.

Dependencies:
- Relates to #158 

Definition of Ready:
- [x] User role and type are identified
- [x] Wireframes completed
- [ ] Design / Solution is accepted by Product Owner

**Comment by dawnbcgov** [comment]
Requires decision from program area to determine whether to proceed, and if so content for #158.

**Comment by kdbelair** [comment]
Propose that we replace the current compliance and enforcement link with the following: https://www2.gov.bc.ca/gov/content/environment/research-monitoring-reporting/reporting/environmental-enforcement-reporting

With the description of: Search the compliance and enforcement database and learn how we coordinate oversight and ensure the process is accountable.

**Comment by dawnbcgov** [comment]
Updated the wireframe with this. To try and keep sentence lengths similar, would this be okay for a description?

"Search the compliance and enforcement database and learn about how we coordinate oversight."

**Comment by kdbelair** [comment]
Yes, approved.
